# Generated by Django 3.0.7 on 2020-10-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.TextField(blank=True, null=True, unique=True, verbose_name='RequirementID')),
                ('job_title', models.TextField(blank=True, null=True, verbose_name='JobTitle')),
                ('job_type', models.TextField(blank=True, null=True, verbose_name='JobType')),
                ('is_remote_location', models.TextField(blank=True, null=True, verbose_name='IsRemoteLocation')),
                ('visa_status', models.TextField(blank=True, null=True, verbose_name='VisaStatus')),
                ('requirement_job_description', models.TextField(blank=True, null=True, verbose_name='RequirementJobDescription')),
                ('actual_requirement', models.TextField(blank=True, null=True, verbose_name='ActualRequirement')),
                ('requirement_skills', models.TextField(blank=True, null=True, verbose_name='RequirementSkills')),
                ('requirement_zip_code', models.TextField(blank=True, null=True, verbose_name='RequirementZIPCode')),
                ('created_date', models.TextField(blank=True, null=True, verbose_name='CreatedDate')),
                ('modified_date', models.TextField(blank=True, null=True, verbose_name='ModifiedDate')),
                ('status', models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'COMPLETED'), (2, 'ERROR')], default=0, verbose_name='RequirementStatus')),
            ],
            options={
                'db_table': 'Requirements',
            },
        ),
        migrations.AlterField(
            model_name='taskexecutiontimings',
            name='task_name',
            field=models.CharField(choices=[('GetCandidateDetails', 'Get Candidate Details'), ('GetRequirementDetails', 'Get Requirement Details'), ('ProcessRequirements', 'Process Requirements')], max_length=100, unique=True),
        ),
    ]
