# Generated by Django 3.0.7 on 2020-10-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecutiontimings',
            options={'verbose_name': 'TaskExecutionTiming', 'verbose_name_plural': 'TaskExecutionTimings'},
        ),
        migrations.AlterModelTable(
            name='taskexecutiontimings',
            table=None,
        ),
    ]
