# Generated by Django 3.0.7 on 2020-10-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_auto_20201026_1419'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requirements',
            table='Requirement',
        ),
        migrations.AlterModelTable(
            name='taskexecutiontimings',
            table='TaskExecutionTiming',
        ),
    ]
