# Generated by Django 3.0.7 on 2020-10-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_taskexecutiontimings_is_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskexecutiontimings',
            name='is_waiting',
            field=models.BooleanField(default=False, verbose_name='Is Task Waiting'),
        ),
    ]
