# Generated by Django 3.0.7 on 2020-10-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0004_auto_20201026_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ModifiedDate'),
        ),
    ]
